export const PERMISSIONS = {

    APPROVE_ORGANIZATION: "APPROVE_ORGANIZATION",
    REJECT_ORGANIZATION: "REJECT_ORGANIZATION",
    VIEW_ALL_ORGANIZATIONS: "VIEW_ALL_ORGANIZATIONS",

    CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
    UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
    DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
    VIEW_EMPLOYEES: "VIEW_EMPLOYEES",

    CREATE_TASK: "CREATE_TASK",
    UPDATE_TASK: "UPDATE_TASK",
    DELETE_TASK: "DELETE_TASK",
    VIEW_TASKS: "VIEW_TASKS",

    UPDATE_ORGANIZATION: "UPDATE_ORGANIZATION",
};