import { PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS = {
    SUPER_ADMIN: [
        PERMISSIONS.APPROVE_ORGANIZATION,
        PERMISSIONS.REJECT_ORGANIZATION,
        PERMISSIONS.VIEW_ALL_ORGANIZATIONS,

        PERMISSIONS.CREATE_EMPLOYEE,
        PERMISSIONS.UPDATE_EMPLOYEE,
        PERMISSIONS.DELETE_EMPLOYEE,
        PERMISSIONS.VIEW_EMPLOYEES,

        PERMISSIONS.UPDATE_ORGANIZATION,

        PERMISSIONS.VIEW_EMPLOYEES,
        PERMISSIONS.CREATE_TASK,
        PERMISSIONS.UPDATE_TASK,
        PERMISSIONS.VIEW_TASKS,
    ],

    ADMIN: [
        PERMISSIONS.CREATE_EMPLOYEE,
        PERMISSIONS.UPDATE_EMPLOYEE,
        PERMISSIONS.DELETE_EMPLOYEE,
        PERMISSIONS.VIEW_EMPLOYEES,

        PERMISSIONS.CREATE_TASK,
        PERMISSIONS.UPDATE_TASK,
        PERMISSIONS.DELETE_TASK,
        PERMISSIONS.VIEW_TASKS,

        PERMISSIONS.UPDATE_ORGANIZATION,
    ],

    EMPLOYEE: [
        PERMISSIONS.VIEW_EMPLOYEES,
        PERMISSIONS.UPDATE_TASK,
        PERMISSIONS.VIEW_TASKS,
    ],
};